# 6. What are the binary sensors in the system?

PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hpcc: <http://example.org/hpcc#>
PREFIX ex: <http://example.org/individuals#>

SELECT ?binary_sensor 
WHERE {
  ?binary_sensor sosa:observes ex:Status . 
  
}