# 2. What is the relation between sensors, observed properties, and target tolerances?

PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hpcc: <http://example.org/hpcc#>
PREFIX ex: <http://example.org/individuals#>
PREFIX qudt: <http://qudt.org/schema/qudt/>

SELECT ?sensor ?property ?tolerance
WHERE {
  ?sensor sosa:observes ?property ;
          hpcc:hasTargetValue ?tolerance .
  ?tolerance qudt:hasUnit ex:K .		  
  
}