# 4. Which sensor measurements deviate more than 30% from their mean values? 

PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX hpcc: <http://example.org/hpcc#>
PREFIX ex: <http://example.org/individuals#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX qudt: <http://qudt.org/schema/qudt/>

SELECT ?observation ?obsValue ?meanValue
WHERE {
  ?observation a sosa:Observation ;
               sosa:madeBySensor ?sensor ;
               sosa:resultTime ?timestamp ;
               sosa:hasSimpleResult ?obsValue .
			   
  ?sensor sosa:madeObservation ?meanObs .
  ?meanObs a hpcc:MeanObservation ;
           sosa:hasSimpleResult ?meanValue .
		   
  # deviation > 10%
  FILTER( ABS(?obsValue - ?meanValue) / ?meanValue > 0.30 )

  FILTER(STRSTARTS(STR(?timestamp), "2026-01-21"))
}
